# Generated by Django 4.1 on 2023-10-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='product_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
