# Generated by Django 4.1 on 2023-10-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_api', '0003_alter_cryptocurrency_base_display_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polkadot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(db_index=True, null=True)),
                ('low', models.FloatField(db_index=True, null=True)),
                ('close', models.FloatField(db_index=True, null=True)),
                ('volume', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='polkadot',
            index=models.Index(fields=['timestamp', 'high'], name='coinbase_ap_timesta_d9bef6_idx'),
        ),
        migrations.AddIndex(
            model_name='polkadot',
            index=models.Index(fields=['timestamp', 'low'], name='coinbase_ap_timesta_deb4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='polkadot',
            index=models.Index(fields=['timestamp', 'close'], name='coinbase_ap_timesta_05312f_idx'),
        ),
    ]
