# Generated by Django 4.1 on 2023-10-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_api', '0006_alter_prediction_unique_together_prediction_crypto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uuid', models.UUIDField()),
                ('currency', models.CharField(max_length=10)),
                ('value', models.FloatField()),
            ],
        ),
    ]
