# Generated by Django 4.1 on 2023-10-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_api', '0007_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('earliest_date', models.DateTimeField()),
            ],
        ),
    ]
