# Generated by Django 4.1 on 2024-06-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_api', '0008_cryptometadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(db_index=True, null=True)),
                ('low', models.FloatField(db_index=True, null=True)),
                ('close', models.FloatField(db_index=True, null=True)),
                ('volume', models.FloatField(null=True)),
                ('sma', models.FloatField(null=True)),
                ('ema', models.FloatField(null=True)),
                ('rsi', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('bollinger_high', models.FloatField(null=True)),
                ('bollinger_low', models.FloatField(null=True)),
                ('vmap', models.FloatField(null=True)),
                ('percentage_returns', models.FloatField(null=True)),
                ('log_returns', models.FloatField(null=True)),
                ('close_higher_shifted_1h', models.BooleanField(null=True)),
                ('close_higher_shifted_24h', models.BooleanField(null=True)),
                ('close_higher_shifted_168h', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='solana',
            index=models.Index(fields=['timestamp', 'close'], name='coinbase_ap_timesta_178d87_idx'),
        ),
    ]
