# Generated by Django 4.1 on 2024-06-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinbase_api', '0010_aave_abt_ach_acs_ada_aergo_aero_agld_aioz_akt_alcx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptometadata',
            name='symbol',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
